###get the service documnet
http://localhost:4004/odata/v4/CatalogService

###Get service metadata
http://localhost:4004/odata/v4/CatalogService/$metadata

###Get service metadata
http://localhost:4004/odata/v2/CatalogService/$metadata

###Get user data
http://localhost:4004/odata/v4/CatalogService/User

###Get user data
http://localhost:4004/odata/v2/CatalogService/User


###validate the data
POST http://localhost:4004/odata/v4/CatalogService/LoginOp
Content-Type: application/json

{
 "USERNAME": "IB03427",
 "PASSWORD": "123459u"
}

###validate the data
POST http://localhost:4004/odata/v2/CatalogService/LoginOp
Content-Type: application/json

{
 "USERNAME": "IB03427",
 "PASSWORD": "12345"
}







